person:
  boss: true
  birth: 2019/12/9
  age: 20
#  interests: [篮球，羽毛球]
  interests:
    - 篮球
    - 足球
  animal: [阿猫,阿狗,小羊]
#  score:
#    english: 60
#    math: 90
  score: {enlish: 60,math: 92}
  salarys:
    - 9999.98
    - 8888.78
  pet:
    name: 阿狗
    weight: 99.99
  allPets:
    sick:
      - {name: 大黄,weight: 99.99}
      - name: 阿狗
        weight: 88.88
      - name: 啊虫
        weight: 66.66
#    health: [{name:大黄,weight:99.99},{},{}]
    health:
      - {name: 阿花,weight: 199.99}
      - {name: 阿红,weight: 129.99}
  user-name: 李四

